var escuCO = {
"type": "FeatureCollection",
"name": "escucal",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": 9011, "LOCALIDAD": "CALETA OLIVIA", "ID": 1, "DENOMINACI": "CPES 6", "DIRECCION": "JULIO BENITEZ", "NIVEL": "SECUNDARIO", "NRO": 6, "BARRIO": "2 DE ABRIL", "TIPO_1": "PUBLICO", "SUP_REGION": null, "MATR_TOTAL": 550, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": null, "MAIL": null, "MODALIDAD": null, "ORIENTACIO": "Cs. Sociales y Hum\/Economía y Adm", "TELEFONO": null, "FECHA_REAL": "30\/04\/2014", "REPITENCIA": "31,6%", "DESERCI�": "4%", "NO_PROMO": "45,8%", "SOBREEDAD": "59%", "ORIENT2013": "Hum y Cs. Sociales\/Economía y Gest. de las Org" }, "geometry": { "type": "Point", "coordinates": [ -67.502193604230257, -46.454721286982043 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": 9011, "LOCALIDAD": "CALETA OLIVIA", "ID": 2, "DENOMINACI": "CPES 13", "DIRECCION": "JUAN GOMEZ", "NIVEL": "SECUNDARIO", "NRO": 13, "BARRIO": "GOBERNADOR GREGORES", "TIPO_1": "PUBLICO", "SUP_REGION": null, "MATR_TOTAL": 469, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": 121, "MAIL": null, "MODALIDAD": null, "ORIENTACIO": "Cs. Sociales\/Turismo", "TELEFONO": null, "FECHA_REAL": "30\/04\/2014", "REPITENCIA": "12,4%", "DESERCI�": "-2,8%", "NO_PROMO": "26,4%", "SOBREEDAD": "35%", "ORIENT2013": "Hum. y Cs. Sociales\/Com. Arte y Diseño" }, "geometry": { "type": "Point", "coordinates": [ -67.52760651720584, -46.454207416721722 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": 9011, "LOCALIDAD": "CALETA OLIVIA", "ID": 3, "DENOMINACI": "CPES 20", "DIRECCION": "JOSE KOLTUM", "NIVEL": "SECUNDARIO", "NRO": 20, "BARRIO": "LOS PINOS", "TIPO_1": "PUBLICO", "SUP_REGION": null, "MATR_TOTAL": 643, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": 1370, "MAIL": "COLEGIO_VEINTE@YAHOO.COM", "MODALIDAD": null, "ORIENTACIO": "Cs. Sociales y Hum\/Cs. Naturales\/Educ. Fisica", "TELEFONO": null, "FECHA_REAL": "30\/04\/2014", "REPITENCIA": "23%", "DESERCI�": "6,2%", "NO_PROMO": "31,9%", "SOBREEDAD": "74%", "ORIENT2013": "Cs. Sociales\/Cs. Naturales" }, "geometry": { "type": "Point", "coordinates": [ -67.540886531558513, -46.443561614295994 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": 9011, "LOCALIDAD": "CALETA OLIVIA", "ID": 4, "DENOMINACI": "CPES 22", "DIRECCION": "LUCIO V. MANSILLA", "NIVEL": "SECUNDARIO", "NRO": 22, "BARRIO": "26 DE JUNIO", "TIPO_1": "PUBLICO", "SUP_REGION": null, "MATR_TOTAL": 398, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": 2545, "MAIL": "POLIMODAL22@YAHOO.COM.AR", "MODALIDAD": null, "ORIENTACIO": "Cs. Sociales y Hum\/Cs. Naturales\/Economía y Adm.", "TELEFONO": null, "FECHA_REAL": "30\/04\/2014", "REPITENCIA": "20,4%", "DESERCI�": "5,5%", "NO_PROMO": "23,4%", "SOBREEDAD": "53%", "ORIENT2013": "Hum y Cs. Sociales\/Economía y Gest. de las Org" }, "geometry": { "type": "Point", "coordinates": [ -67.52688195835583, -46.442098480654224 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": 9011, "LOCALIDAD": "CALTEA OLIVIA", "ID": 5, "DENOMINACI": "CPES 27", "DIRECCION": "GOBERNADOR", "NIVEL": "SECUNDARIO", "NRO": 27, "BARRIO": "SAN CAYETANO", "TIPO_1": "PUBLICO", "SUP_REGION": null, "MATR_TOTAL": 387, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": 939, "MAIL": "COLEGIOPROV27@YAHOO.COM.AR", "MODALIDAD": null, "ORIENTACIO": "Cs. Sociales y Humanidades", "TELEFONO": null, "FECHA_REAL": "30\/04\/2014", "REPITENCIA": "13,2%", "DESERCI�": "1,3%", "NO_PROMO": "22,2%", "SOBREEDAD": "64%", "ORIENT2013": "Hum y Cs. Sociales (Socio-comunitario)" }, "geometry": { "type": "Point", "coordinates": [ -67.53945171346561, -46.447660817280862 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": 9011, "LOCALIDAD": "CALETA OLIVIA", "ID": 6, "DENOMINACI": "CPES 42", "DIRECCION": "ENTRE RIOS", "NIVEL": "SECUNDARIO", "NRO": 42, "BARRIO": "ROTARY 23", "TIPO_1": "PUBLICO", "SUP_REGION": null, "MATR_TOTAL": 192, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": 2784, "MAIL": null, "MODALIDAD": null, "ORIENTACIO": "Cs. Sociales y Humanidades", "TELEFONO": null, "FECHA_REAL": "30\/04\/2014", "REPITENCIA": "37,5%", "DESERCI�": "2,6%", "NO_PROMO": "45,8%", "SOBREEDAD": "78%", "ORIENT2013": null }, "geometry": { "type": "Point", "coordinates": [ -67.556482040067436, -46.445334853632353 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": 9011, "LOCALIDAD": "CALETA OLIVIA", "ID": 7, "DENOMINACI": "CPES 43", "DIRECCION": "JUAN SANTOS CARPIO", "NIVEL": "SECUNDARIO", "NRO": 43, "BARRIO": "17 DE OCTUBRE", "TIPO_1": "PUBLICO", "SUP_REGION": null, "MATR_TOTAL": 146, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": 575, "MAIL": null, "MODALIDAD": null, "ORIENTACIO": "Artes Visuales", "TELEFONO": null, "FECHA_REAL": "30\/04\/2014", "REPITENCIA": "22,6%", "DESERCI�": "2,7%", "NO_PROMO": "20,5%", "SOBREEDAD": "68%", "ORIENT2013": null }, "geometry": { "type": "Point", "coordinates": [ -67.520883708604032, -46.465327091843953 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": null, "LOCALIDAD": null, "ID": null, "DENOMINACI": "INDUSTRIAL 1", "DIRECCION": null, "NIVEL": null, "NRO": 1, "BARRIO": null, "TIPO_1": null, "SUP_REGION": null, "MATR_TOTAL": null, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": null, "MAIL": null, "MODALIDAD": null, "ORIENTACIO": "Informática\/MMO\/Ind. de Procesos\/Electromecánica", "TELEFONO": null, "FECHA_REAL": null, "REPITENCIA": null, "DESERCI�": null, "NO_PROMO": null, "SOBREEDAD": null, "ORIENT2013": "Informática\/MMO\/Ind. de Procesos\/Electromecánica" }, "geometry": { "type": "Point", "coordinates": [ -67.529529986139622, -46.446056140235456 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": null, "LOCALIDAD": null, "ID": null, "DENOMINACI": "EBIMAL 1", "DIRECCION": null, "NIVEL": null, "NRO": 100, "BARRIO": null, "TIPO_1": null, "SUP_REGION": null, "MATR_TOTAL": null, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": null, "MAIL": null, "MODALIDAD": null, "ORIENTACIO": "Biología M, Pesquería y Lab", "TELEFONO": null, "FECHA_REAL": null, "REPITENCIA": null, "DESERCI�": null, "NO_PROMO": null, "SOBREEDAD": null, "ORIENT2013": "Biología M, Pesquería y Lab" }, "geometry": { "type": "Point", "coordinates": [ -67.508924187416284, -46.460882334274459 ] } },
{ "type": "Feature", "properties": { "CUE": null, "CI": null, "COD_POSTAL": null, "LOCALIDAD": null, "ID": null, "DENOMINACI": "INDUSTRIAL 10", "DIRECCION": null, "NIVEL": null, "NRO": 10, "BARRIO": null, "TIPO_1": null, "SUP_REGION": null, "MATR_TOTAL": null, "MATR_MANAN": null, "MATR_TARDE": null, "MATR_NOCHE": null, "RED": null, "ALTURA": null, "MAIL": null, "MODALIDAD": null, "ORIENTACIO": "Tec. del Automotor\/Tec. en Electrónica", "TELEFONO": null, "FECHA_REAL": null, "REPITENCIA": null, "DESERCI�": null, "NO_PROMO": null, "SOBREEDAD": null, "ORIENT2013": null }, "geometry": { "type": "Point", "coordinates": [ -67.51176663801786, -46.450613239395835 ] } }
]
}
